### ISSUE TITLE
Không thấy nút tham gia sau khi đăng nhập

### ISSUE THREAD

**Issue by tamnguyenvan** [aivivn/aivivn_issues#2]
Chào admin. Sau khi mình đăng nhập thì không thấy hiển thị nút Tham gia. Lần đăng nhập trước (1 2 ngày trước) thì vẫn xuất hiện.

**Comment by tiepvupsu** [comment]
Khi bạn đã tham gia rồi thì không còn nút đó nữa.

**Comment by tamnguyenvan** [comment]
Cảm ơn ad. Bấm vào tên cuộc thi thì được rồi :)
