### ISSUE TITLE
Không đăng nhập được

### ISSUE THREAD

**Issue by ghost** [aivivn/aivivn_issues#3]
Mình ko biết web có chặn IP hay gì không mà mình ở nước ngoài không thể đăng nhập được? Click vào button đăng nhập không có phản hồi gì. 

Mong sớm nhận được phản hồi.
Thanks

**Comment by CarloNguyen** [comment]
Bạn đã fix được lỗi này chưa?

**Comment by sonvx** [comment]
Thực ra đây không phải là lỗi mà là **không thông báo khi user/password bị sai**. Nếu bạn đăng ký email và user khác nhau, nhưng ko dùng user/password để đăng nhập mà dùng "email/password" để đăng nhập thì sẽ không đc. Tương tự với user/password không tồn tại chưa có báo lỗi login.

**Comment by ghost** [comment]
Mình đã đăng nhập được rồi. Thanks!

**Comment by tiepvupsu** [comment]
@cuongpxu nếu bạn không thấy vấn đề gì nữa thì close issue giúp mình. Cảm ơn bạn.
