### ISSUE TITLE
Nên tắt hỗ trợ tiếng Việt có dấu cho mật khẩu đăng nhập

### ISSUE THREAD

**Issue by rednam-ntn** [aivivn/aivivn_issues#4]
mình nghĩ các bạn nên tắt hỗ trợ tiếng Việt cho mật khẩu khi đăng ký mới tài khoản, rất dễ gây nhầm lẫn và tiềm ẩn lỗi 🐛🐛🐛

**Comment by cinoss** [comment]
@rednam-ntn  Hiện tại password đã không chấp nhận tiếng việt có dấu trong mật khẩu
